### ISSUE TITLE
Как сделать в плагине ошибку tooltip ?

### ISSUE THREAD

**Issue by leonidkuznetsov18** [CSSSR/jquery.csssr.validation#1]
Как в вашем плагине реализовать нечто подобное? 
![image](https://cloud.githubusercontent.com/assets/9495532/12507215/01515422-c0fd-11e5-98a0-433bf142cb90.png)
и что бы моя верстка имела вид 
![image](https://cloud.githubusercontent.com/assets/9495532/12507259/4207190c-c0fd-11e5-944e-a784027d5453.png)

**Comment by azanov** [comment]
Пример: https://jsfiddle.net/coder13/gyvuvzd0/
